### ISSUE TITLE
Initializers?

### ISSUE THREAD

**Issue by joshmn** [bobf/devpack#1]
Any interest in having `.devpack_initializers` act like `config/initializers`? Love this idea but hate the thought of polluting our initializers with:

```
if defined?(Bullet)
  ... 
end
```

**Comment by bobf** [comment]
@joshmn I will definitely give this some thought - I use Rails a lot so can see the benefit here.

I'll see if I've had any bright ideas by the weekend and then have a go at putting something together. I'll keep you posted.

Thanks for the feedback !

**Comment by bobf** [comment]
@joshmn I've just pushed _Devpack_ `0.2.0` which provides support for a `.devpack_initializers` directory.

When Rails is detected the `after_initialize` hook is used to load any `.rb` file found in that directory, otherwise they are loaded immediately after the `.devpack` configuration file has loaded.

Let me know how you get on & thanks for the idea.
